---
#####
# These settings are synced to GitHub
# by https://probot.github.io/apps/settings/
#
# See https://docs.github.com/en/rest/reference/repos#update-a-repository for
# all available settings.
#
# _extends: '.github'
repository:
  name: .github
  topics: "npm, github, actions, templates, probot"
  description: "🐙 natterstefan's user-wide settings"
  homepage: "https://github.com/natterstefan"
  default_branch: main
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_squash_merge: true
  has_downloads: true
  has_issues: true
  has_projects: false
  has_wiki: false
  # private: true

branches:
  - name: main
    protection:
      enforce_admins: false
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
        dismissal_restrictions:
          teams: []
          users: []
      required_status_checks:
        strict: true
      restrictions:
        teams: []
        users: []

labels:
  - { color: "#80C000", name: "feature", description: "" } # Green
  - { color: "#FF8000", name: "refactor", description: "" } # Orange
  - { color: "#C00000", name: "bug", description: "" } # Red
  - { color: "#FFC000", name: "chore", description: "" } # Yellow
  - { color: "#00C0FF", name: "ci", description: "" } # Light Blue
  - { color: "#C080FF", name: "docs", description: "" } # Light Purple

  - { color: "#7057ff", name: "good first issue", description: "" } # Very Light Blue
  - { color: "#7057ff", name: "help wanted", description: "" } # Very Light Blue

  - { color: "#000000", name: "question", description: "" } # Black

  - { color: "#C00000", name: "blocked", description: "" } # Red
  - { color: "#DDDDDD", name: "duplicate", description: "" } # Gray
  - { color: "#DDDDDD", name: "invalid", description: "" } # Gray
  - { color: "#DDDDDD", name: "wontfix", description: "" } # Gray
